baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'wvu-ds-v2-hugo'
<<<<<<< HEAD
=======

[module]
  [[module.imports]]
    path = 'github.com/adamglenn/wvu-ds-v2-hugo-modules-hero'
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
>>>>>>> b265ed1 (Adding some content.)
